version: '3.9'

services:
  django:
    image: django-docker # Khong can docker image tag de khoa version khi run lenh docker-compose up --build de cho luc run luon lay version latest cua image
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    