# Generated by Django 4.2.5 on 2023-10-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_avatar_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
